<a href="https://colab.research.google.com/github/HafeezCodes/numpy-matrices-exercise-1/blob/main/numpy_matrices_exercise_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [57]:
import numpy as np

In [58]:
# revenue and expenses are two 3x3 matrices that represents the sales and expenses of 3 different products in 3 different years
# every column represent sales in a specific year
# every row represents a specific product
revenue  = np.array([[100,150,200],[250,300,350],[400,450,500]])
print("revenue = \n", revenue)
expenses = np.array([[10,15,20],[25,30,35],[40,45,50]])
print("expenses = \n", expenses)
profit = revenue - expenses
print("profit = revenue - expenses = \n", profit)

revenue = 
 [[100 150 200]
 [250 300 350]
 [400 450 500]]
expenses = 
 [[10 15 20]
 [25 30 35]
 [40 45 50]]
profit = revenue - expenses = 
 [[ 90 135 180]
 [225 270 315]
 [360 405 450]]


In [59]:
# price_per_unit here is a 1x3 row vector matrix
# row represents the price per unit
# Each column represent a different product
price_per_unit = np.array([100,500,1000])
print("price_per_unit = \n", price_per_unit)

# units is 3x3 matrix where each row represents a specific product and each column a specific year
units = np.array([[30,40,50],[5,10,15],[2,5,7]])
print("units = \n", units)

# to calculate how many units sold of all products (3 in this case) in a specific year, we multiply these 2 matrices using dot product
units_sold_per_year = np.dot(price_per_unit, units)
print("units_sold_per_year = \n", units_sold_per_year)

price_per_unit = 
 [ 100  500 1000]
units = 
 [[30 40 50]
 [ 5 10 15]
 [ 2  5  7]]
units_sold_per_year = 
 [ 7500 14000 19500]


In [60]:
# revenue_in_dollars is a 4x3 matrix that represents revenue of 4 companies in 3 different years in US dollars
# Using numpy we will convert this into pakistani rupees
# 1 USD = 275 pkr
revenue_in_dollars = np.array([[200,220,250],[68,79,105],[110,140,180],[80,85,90]])
revenue_in_pkr = revenue_in_dollars * 275
print("revenue in USD = \n", revenue_in_dollars)
print("revenue in PKR = \n", revenue_in_pkr)

revenue in USD = 
 [[200 220 250]
 [ 68  79 105]
 [110 140 180]
 [ 80  85  90]]
revenue in PKR = 
 [[55000 60500 68750]
 [18700 21725 28875]
 [30250 38500 49500]
 [22000 23375 24750]]


In [61]:
# units_sold is a 3x3 matrix which represents the sales of 3 different flowers in 3 different months
units_sold = np.array([[50,60,25],[10,13,14],[40,50,60]])
print("units_sold = \n", units_sold)

# price_per_unit is a 3x1 column vector matrix which represents the price per unit of each type of flower
price_per_unit = np.array([[1000],[800],[1700]])
print("price_per_unit = \n", price_per_unit)

# total_sales is a 3x1 column vector matrix which represents the total sales of each type of flower
total_sales = np.dot(units_sold, price_per_unit)
print( "total sales = \n", total_sales)


units_sold = 
 [[50 60 25]
 [10 13 14]
 [40 50 60]]
price_per_unit = 
 [[1000]
 [ 800]
 [1700]]
total sales = 
 [[140500]
 [ 44200]
 [182000]]
